### ISSUE TITLE
add support mjml2json

### ISSUE THREAD

**Issue by splainez** [danihodovic/mjml-http-server#91]
Hello, would it be possible to add support for [mjml2json](https://github.com/mjmlio/mjml2json)/[json2mjml ](https://github.com/mjmlio/json2mjml)on a new endpoint?

**Comment by danihodovic** [comment]
I've never seen MJML in JSON format, do you have a link to documentation?

Is it possible? Yes. Is it necessary? I don't know yet. What are the use cases for JSON mjml usage?

**Comment by splainez** [comment]
The official documentation is short https://mjml.io/documentation/#using-mjml-in-json

Use cases, for example [topol.io](https://topol.io/), imports mjml but only in json format

**Comment by danihodovic** [comment]
What is it that you're trying to achieve? Looking at Topol briefly it seems that you might drag and drop a UI in Topol, export it as JSON and render it with a MJML server. Is my assumption correct?

**Comment by splainez** [comment]
yes, more or less, if you take a mjml template from other system in xml, before to import to the editor need transform to json, and after when you save you need transform json to xml

im looking for a docker image with 3 endpoint, render/mjml2json/json2mjml

I could do a pull request if you prefer

**Comment by danihodovic** [comment]
Is this something that's done automatically in your system or a manual action? If it's done manually - isn't it easier to use the mjml-cli?

**Comment by splainez** [comment]
Yes, I am doing it manually, but I am looking to do it automatically.

**Comment by danihodovic** [comment]
Submit a PR and I'll have a look. I'm initially thinking that it may be better to indicate in the payload (HTTP body) what's being sent (xml vs. json) and parse the payload based on that.
